### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Sainidi/grid-template#1]
1)
вид не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/122867616-73d38680-d332-11eb-92ec-379bc53f6562.png)

2)
hover не отрабатывает
![image](https://user-images.githubusercontent.com/8464662/122867650-7fbf4880-d332-11eb-8340-a471d0059727.png)

3)
некорректное поведение изображения, не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/122867664-86e65680-d332-11eb-8b3d-a796d6f0bd71.png)

**Comment by Alecto** [comment]
4)
вид не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/122940611-4bbd4500-d37d-11eb-80d8-f5e863b948ba.png)

**Comment by Sainidi** [comment]
> вид не соответствует задаче
> ![image](https://user-images.githubusercontent.com/8464662/122940611-4bbd4500-d37d-11eb-80d8-f5e863b948ba.png)

Исправил

**Comment by Alecto** [comment]
2 ссылки пожалуйста

вт, 22 июн. 2021 г. в 17:25, Sainidi ***@***.***>:

**Comment by Sainidi** [comment]
https://sainidi.github.io/grid-template/
https://github.com/Sainidi/grid-template.git

**Comment by Alecto** [comment]
правильно, работа принята

вт, 22 июн. 2021 г. в 17:32, Sainidi ***@***.***>:

**Comment by Alecto** [comment]
кому работу ставить? в переписке через гитхаб инфа потерялась

вт, 22 июн. 2021 г. в 17:38, Андрей Фоменко ***@***.***>:

**Comment by Sainidi** [comment]
> кому работу ставить? в переписке через гитхаб инфа потерялась вт, 22 июн. 2021 г. в 17:38, Андрей Фоменко ***@***.***>:
> […](#)






Сайниди Александр, сб/вс 9-30

Сайниди Александр, сб/вс 9-30. Еще убрал лишний селектор цвета в этой форме, но вы и с ним засчитали)

**Comment by Alecto** [comment]
вт, 22 июн. 2021 г. в 18:00, Sainidi ***@***.***>:

> кому работу ставить? в переписке через гитхаб инфа потерялась вт, 22 июн.
> 2021 г. в 17:38, Андрей Фоменко *@*.***>:
> … <#m_7768860736258929787_>
>
> Сайниди Александр, сб/вс 9-30.
>
спасибо, отметил


> Еще убрал лишний селектор цвета в этой форме, но вы и с ним засчитали)
>
отлично, мог чтото пропустить, человеческий фактор.

**Comment by Sainidi** [comment]
Сайниди Александр, сб/вс 9-30
Я в гитхаб ответил, но наверное не пришёл ответ

Вт, 22 июня 2021 г. в 20:35, Andrey ***@***.***>:
